name: build-ubuntu_18_04

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: sudo apt install doxygen virtualenv graphviz
    - name: Build Zserio
      run: scripts/build.sh all-linux64
    - name: Pack Zserio release
      run: scripts/release.sh
    - name: Run Zserio tests
      run: scripts/test.sh all-linux64
